### ISSUE TITLE
Wrong directory name (META_INF) in doc and readme

### ISSUE THREAD

**Issue by Troxid** [scijava/native-lib-loader#16]
Hello. In [documentation](https://github.com/scijava/native-lib-loader/blob/master/src/main/java/org/scijava/nativelib/NativeLibraryUtil.java#L45) and readme file written next directory `META_INF` but in code you search in this [path](https://github.com/scijava/native-lib-loader/blob/master/src/main/java/org/scijava/nativelib/NativeLibraryUtil.java#L169) (`META-INF`).

**Comment by ctrueden** [comment]
Thanks for pointing that out!
