### ISSUE TITLE
ARM 64-bit support

### ISSUE THREAD

**Issue by extensia** [scijava/native-lib-loader#17]
The NativeLibraryUtil getProcessor method currently does not differentiate between the 32-bit and 64-bit ARM platforms. It would be helpful to add 64-bit ARM support since it is now officially supported by Oracle and ARM 64 hardware is becoming increasingly common.

**Comment by ctrueden** [comment]
@extensia Would you care to try your hand at a PR? We are here if you have questions.

**Comment by extensia** [comment]
Sure thing. I just added a pull request. Thx

**Comment by ctrueden** [comment]
Thanks! For reference, the PR is #18, and it is now merged. :beers:

**Comment by extensia** [comment]
Excellent. Any idea when the next package release will occur? We have an internal build, but would prefer to use an official build when it becomes available.

**Comment by ctrueden** [comment]
> Any idea when the next package release will occur?

Version 2.2.0 [now exists](https://oss.sonatype.org/#nexus-search;gav~org.scijava~native-lib-loader~2.2.0~~).

**Comment by cmosh** [comment]
I am also interested in using this for arm64 and the issue seems resolved but I'm not sure since it is still open, could you please close it if it was in fact resolved

**Comment by ctrueden** [comment]
@cmosh Thanks for the reminder. Assuming all is well now, I'm closing the issue. @extensia please reopen if things are still not satisfactory.
