### ISSUE TITLE
Problems with having the library on the module path

### ISSUE THREAD

**Issue by alexanderkjall** [scijava/native-lib-loader#24]
I'm trying to use a library (org.testcontainers) that uses this library on the module path in java 10, and I'm getting this warning:

```
Can't extract module name from native-lib-loader-2.0.2.jar: native.lib.loader: Invalid module name: 'native' is not a Java identifier
```

**Comment by ctrueden** [comment]
@alexanderkjall Sorry for the delayed reply. I thought this issue was fixed awhile ago; see e8e4e5cbb18f9ce857d8a44a7aa7a9f7f04515ef and scijava/pom-scijava-base#5.

Is it still a problem with native-lib-loader 2.3.2?

**Comment by alexanderkjall** [comment]
Looks like the version that testcontainers use is 2.0.2, and if I upgrade to 2.3.2 the problems disappear, thanks for the update, I'll close this and update the testcontainers bug.

**Comment by ctrueden** [comment]
Great, thanks @alexanderkjall!
