### ISSUE TITLE
Crash on Android 6 Arm v7

### ISSUE THREAD

**Issue by hgourvest** [scijava/native-lib-loader#26]
I use a library that use this loader, it works on Android 8 but it crash on Android 6.

**Comment by Shaquu** [comment]
Can you provide stacktrace?

**Comment by hgourvest** [comment]
12-18 15:02:13.596 8391-8391/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.organisation.appname, PID: 8391
    java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
        at org.scijava.nativelib.BaseJniExtractor.getTempDir(BaseJniExtractor.java:125)
        at org.scijava.nativelib.WebappJniExtractor.<init>(WebappJniExtractor.java:69)
        at org.scijava.nativelib.NativeLoader.<clinit>(NativeLoader.java:103)
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)

**Comment by Shaquu** [comment]
Android with api version below 26 doesn't support java.nio.file

Your options:

1. don't use Android below 8 (it's not your solution I believe)
2. Try to clone my fork and look if it works for you. If not then we will try to fix your issue :)

I removed java.nio.file and used java.io.file instead. It possible will work but I don't have Android to check this.
https://github.com/Shaquu/native-lib-loader/tree/AndroidApi%3C26Support

**Comment by hgourvest** [comment]
Actually the use of this library is pointless on Android, the system already extract lib to the right place.
What about testing this: System.getProperty("java.vm.vendor").contains("Android")
So you can call System.loadLibrary without doing anything else.

**Comment by ctrueden** [comment]
> the system already extract lib to the right place

Really? Surely there must be certain conventions that the Android platform adheres to for unpacking native libraries though, no? The convention here is to put it in `natives/`. Does Android really magically do it? I'm skeptical.

> Android with api version below 26 doesn't support java.nio.file
> I removed java.nio.file and used java.io.file instead.

I was going to propose the same thing. This library was previously built with Java 6, and we took care to use a smaller subset of the core Java API. We could return to that, if it would be helpful. Or keep at Java 8 but avoid usage of java.nio. I do not feel strongly. Pull requests that address these sorts of issues are very welcome.

**Comment by hgourvest** [comment]
When apk file is installed all libs coresponding to the platform are extracted in
/data/app/org.organisation.app/lib/%platform%
you can see that on a rooted device

**Comment by ctrueden** [comment]
@hgourvest Interesting—so it scans the entire JAR contents and analyzes each file to discern the architecture etc. and then extracts it? Crazy...

**Comment by Shaquu** [comment]
So my question is what library do you use @hgourvest ?

**Comment by hgourvest** [comment]
I am not interested to make it working on Android since the library would be extracted twice. 
I see 2 solutions:
1) Specify not to use this library if you target Android.
2) Detect Android using "java.vm.vendor" property as I said.

**Comment by ctrueden** [comment]
@hgourvest It already does try to load from the native library path first:

https://github.com/scijava/native-lib-loader/blob/native-lib-loader-2.3.2/src/main/java/org/scijava/nativelib/NativeLoader.java#L131-L143

Only if the initial load fails does it try to extract anything. So this should already work on Android, no?

**Comment by hgourvest** [comment]
@ctrueden @Shaquu You're right, I tested it, and I confirm it don't crash anymore on Android 6 and the library is actually loaded. I hope it is still working as expected on other systems and you will provide a new official release soon.

**Comment by ctrueden** [comment]
Thanks @hgourvest for testing!

@Shaquu Would you be able to file a PR with the changes removing use of `java.nio`?

**Comment by Shaquu** [comment]
@ctrueden yes but I would like to test it on other platforms before PR.

**Comment by Shaquu** [comment]
@ctrueden there is PR #27

**Comment by ctrueden** [comment]
Fixed by #27.
