### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Shaquu** [scijava/native-lib-loader#28]
Today I got an issue while building my app.
`java.lang.UnsupportedClassVersionError: org/scijava/nativelib/JniExtractor : Unsupported major.minor version 52.0`

It's obviously very clear.

I need to compile code in java 7 as my app and environment is stick to java 7 but native-lib-loader is build using java 8.
I would encourage you to change travis build script to build using java 7. I think there is no need to abandon java 7 yet. And as code fully support java 7 then it shouldn't be a problem.

**Comment by Shaquu** [comment]
@ctrueden since some people can consider switching java version a major change then I need you acceptance for this issue.

**Comment by imagejan** [comment]
See https://github.com/imagej/imagej/issues/135 for the reasons why ImageJ (and SciJava) switched to Java 8. (It might be ok though for `native-lib-loader` to still build with Java 7...)

**Comment by ctrueden** [comment]
I tried to fix this with 27b40c99558a82687b9514d43d008702507496a3. @Shaquu Please try the [latest snapshot build](https://maven.imagej.net/service/local/artifact/maven/redirect?r=snapshots&g=org.scijava&a=native-lib-loader&v=LATEST&e=jar) and let me know if there continue to be problems.

**Comment by bmhm** [comment]
You could even target java 1.6. To do this, all you need is to replace a single diamond operator and three try-with-resources.

To verify you're not using Java 1.7 API (you actually don’t), just add some compiler properties and the maven animal sniffer plugin. You can still build using java 1.8 or even 11. Pull request is on the way.

**Comment by bmhm** [comment]
Here you go: 
https://github.com/scijava/native-lib-loader/pull/30

**Comment by Shaquu** [comment]
@bmhm thanks! I vote for that. I will close this Issue as it's quite old and actually resolved.
Thanks you again for new PR!

**Comment by ctrueden** [comment]
I released [native-lib-loader 2.3.3](https://oss.sonatype.org/#nexus-search;gav~org.scijava~native-lib-loader~2.3.3~~) including this patch. I double checked that the release artifact has class version corresponding to Java 6; please test and report back if any problems.
