### ISSUE TITLE
Runtime error 

### ISSUE THREAD

**Issue by sken77** [scijava/native-lib-loader#34]
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I get the following error after calling `NativeLoader.loadLibrary(...)` im calling it inside a Static Initializer

**Comment by ctrueden** [comment]
The native-lib-loader uses [SLF4J](http://www.slf4j.org/) for logging. Those messages are a warning that your project did not add any SLF4J binding, so any log messages will not be sent anywhere. See [this](http://www.slf4j.org/manual.html#hello_world) and [that](http://www.slf4j.org/manual.html#swapping) sections of the SLF4J manual for some explanations about it.

Simplest way forward to eliminate the warnings is to add a dependency on `org.slf4j:slf4j-nop` to your project. Or if you want to see log messages on stderr, you can use `org.slf4j:slf4j-simple`. Or if you want to integrate the SLF4J logging with another framework like logback you can use the affiliated binding e.g. `slf4j-log4j12`.
